[package]
name = "r_dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
flexi_logger = "0.22"
clap = { version = "3.0", features = ["derive"] }